name: flutter_lightech_lint_rules
description: Lint rules for "LighTech" company for Dart and Flutter projects.
version: 1.0.0
homepage: null

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
